# Generated by Django 5.0.6 on 2024-09-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('transfer', 'transfer'), ('tulpar', 'tulpar')], max_length=255, verbose_name='Тип')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('geolocation', models.CharField(max_length=255, verbose_name='Адрес')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя и фамилия')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Номер телефона')),
                ('transport_code', models.IntegerField(blank=True, null=True, verbose_name='Код транспорта')),
                ('receipt_number', models.PositiveIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Платежи',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
