# Generated by Django 5.0.6 on 2024-09-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_payment_user_payment_users'),
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payments',
            field=models.ManyToManyField(related_name='user_payments', to='payments.payment'),
        ),
    ]
